    // Unexpire passwords to simplify dev mode. Comment these two lines for Production use
    zn "%SYS"
    Do ##class(Security.Users).UnExpireUserPasswords("*")


    // create SC namespace
    do $SYSTEM.OBJ.Load("/opt/irisbuild/Installer.cls", "ck")
    set sc = ##class(App.Installer).setup()

    // load all the code of the project as a ZPM package
    zn "SC"
    do $SYSTEM.OBJ.Load("/opt/irisbuild/Version.cls", "ck")
    set sc = ##class(App.Version).logVersion()

    do $SYSTEM.OBJ.Load("/opt/irisbuild/Installer.cls", "ck")
    do ##class(App.Installer).installZPM()
    do ##class(App.Installer).loadZPMPackage()


    halt
